name: Clean and Merge

on:
  pull_request:
    types: [labeled]
    branches: [main]

jobs:
  clean_and_merge:
    if: contains(github.event.pull_request.labels.*.name, 'ready-to-merge')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run Cleaning Script
        run: |
          git checkout main -- repo_assistant_config.json
          rm thread_id || echo "No thread_id file to remove"
          rm assistant_issue_comment.txt || echo "No assistant_issue_comment file to remove"

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automated cleanup [skip ci]" || echo "No changes to commit"

      - name: Push Changes
        run: git push origin HEAD:${{ github.event.pull_request.head.ref }}

      - name: Merge Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            })
