name: Create and Update Repo Assistant on Branch Creation

on:
  create:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  create_update_repo_assistant:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Extract Branch Name
      id: extractbranch
      run: echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Create Repo Assistant
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python tools/create_repo_assistant.py ${{ github.repository }} ${{ env.branch_name }}

    - name: Update Assistant Instructions
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python tools/update_assistant.py ${{ env.branch_name }}

    - name: Clean and Update Vector Store
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python tools/clean_update_vector_store.py $(pwd)

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
git add .
git commit -m "Update Assistant for ${{ env.branch_name }}" || echo "Nothing to commit"
git push origin ${{ env.branch_name }}
