name: Create and Update Repo Assistant on Branch Creation

on:
  create:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  create_update_repo_assistant:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Create Repo Assistant
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        pip install ai-assistant
        ai_init_repo

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update Assistant for ${{ env.branch_name }}"
        git push origin ${{ env.branch_name }}
