name: Handle Branch Deletion

on:
  delete:
    branches:
      - '**'

jobs:
  handleDeletion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.before }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get Assistant and Vector Store IDs
      run: |
        python3 tools/fetch_ids_from_names.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Delete Assistant and Vector Store
      run: python tools/delete_assistant.py $repo_assistant_id $repo_vector_store_id
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
