name: Handle Branch Deletion

on:
  delete:
    branches:
      - '**'

jobs:
  handleDeletion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Extract branch name
      id: extractbranch
      run: echo "::set-output name=branch::${GITHUB_REF##*/}"

    - name: Delete Assistant and Vector Store
      run: python tools/delete_assistant.py ${{ steps.extractbranch.outputs.branch }}
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
