name: Run Assistant on Issue

on:
  issues:
    types: [opened]

jobs:
  run-assistant:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Assistant Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          ISSUE_TITLE="${{ fromJson(steps.get_issue.outputs.data).title }}"
          ISSUE_BODY="${{ fromJson(steps.get_issue.outputs.data).body }}"
          python tools/run_assistant.py "New issue created: ${ISSUE_TITLE}
          Description: ${ISSUE_BODY}
          You should do your best to propose a PR to this issue or, at least, generate a comment to help the issue's author." --no-interactive
