# This workflow automatically updates the ai_assistant instruction with the repository structure
# whenever a push is made to the main branch.

name: Update Assistant

on:
  push:
    branches:
      - main

jobs:
  update_instructions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Update Assistant Instructions
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pip install .
          ai_update_assistant .

